project:
  type: website

website:
  title: "web2"
  navbar:
    left:
      - href: LWF_models.qmd
        text: LWF Models
      - href: R_functions.qmd
        text: R Functions
      - href: run_RTMB.qmd
        text: Run RTMB

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

